### ISSUE TITLE
Error connection refused

### ISSUE THREAD

**Issue by Martinvdm** [pschmitt/docker-plantgateway#5]
Hi i am getting Connection Refused.

```
Fri, 03 Aug 2018 22:52:36 INFO     PlantGateway version 0.5.0
Fri, 03 Aug 2018 22:52:36 INFO     loaded config file from /root/.plantgw.yaml
Fri, 03 Aug 2018 22:52:36 INFO     Getting data from sensor Achtertuin
Fri, 03 Aug 2018 22:52:36 ERROR    could not read data from C4:7C:8D:66:E8:89 (Achtertuin) with reason: [Errno 111] Connection refused
Fri, 03 Aug 2018 22:52:36 WARNING  fail_silent is set for sensor Achtertuin, so not raising an exception.
```
plantgw:
```sensors:
    - mac: C4:7C:8D:66:E8:89
      alias: Achtertuin
      fail_silent:
```
using latest version in Docker. Docker config:
```
  plantgateway:
    image: this_image:latest
    container_name: PlantGateway
    restart: always
    network_mode: host
    volumes:
      - /home/docker/plantgateway/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```
